services:
  - type: web
    name: jess-backend
    env: python
    rootDir: .
    buildCommand: pip install -r ./requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000
      - key: CORS_ORIGINS
        value: "https://jessvoiceagentmodule-front-end.onrender.com"

  - type: web
    name: jess-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://jessvoiceagentmodule.onrender.com
